### PR TITLE
Fix #15

### LINKED ISSUE #15: NeinLinq injects hiding member in injectable member of declaring type
> `new` is evil 
>     - A wise man

When a base class instance-member declares itself to be injectable, NeinLinq would also inject a member of a derived class, that overrides the base member.
While this behavior conforms to the behavior of the CLR for `virtual` members, it does not for members that were hidden by using `new`.

FunctionsBase.cs:
``` C#
[InjectLambda(nameof(VelocityCalculationExpression))]
public double VelocityCalculation(Dummy value)
{
    throw new NotSupportedException();
}

public Expression<Func<Dummy, double>> VelocityCalculationExpression()
{
    return v => v.Distance / v.Time;
}
```

ConcreteFunctions.cs
``` C#
public new Expression<Func<Dummy, double>> VelocityCalculationExpression()
{
    throw new InvalidOperationException();
}
```
ConcreteQueryTests.cs:
``` C#
[Fact]
public void ShouldSucceedWithHiddenSibling()
{
    var query = from d in data.ToInjectable()
	            select ((FunctionsBase)functions).VelocityCalculation(d);

    var result = query.ToList();
	
    Assert.Equal(new[] { 200, .0, .1 }, result);
}
```
^ Fails by throwing the Exception.

* For `virtual` (and therefore also for `abstract`) members the current behavior conforms to the behavior of the CLR
* For nonvirtual-members that are hidden with `new`, the current behavior is wrong, when the target type of the injectable method is *not* the hiding type.
    * Note: I have no clue if that also applies for types, that derive from the **hiding type** - most likely it does. (Imho ones HD should get formatted by the compiler when trying to do that, but it's valid .NET-Code and NeinLinq should define how to deal with it.)

Completely conforming to the behavior of the CLR could end up in a lookup hell with a major influence on performance. Since using `new` in domain design, the main use of NeinLinq, is considered to be an anti-pattern anyway, I think it would be sufficient to generally prohibit the injection of hiding members by throwing an exception if that is attempted.

### PR DESCRIPTION
**Pull request by axelheer**
cc @peterwurzinger

### CODE REVIEW

File: src/NeinLinq/InjectLambdaSignature.cs [hunk 1]
```diff
@@ -101,21 +103,32 @@ private static Exception FailFactory(Type target, string method, string error)
...
                         break;
                 }
 
                 // non-matching parameter type?
                 if (index != parameterTypes.Length)
                     continue;
 
-                return candidate;
+                // There can only be one!
+                if (result != null)
```
Comment (peterwurzinger) [inline src/NeinLinq/InjectLambdaSignature.cs]: what about
`result is { }` 

:head_smashing_desk:

File: src/NeinLinq/InjectLambdaSignature.cs [hunk 2]
```diff
@@ -101,21 +103,32 @@ private static Exception FailFactory(Type target, string method, string error)
...
+                {
+                    // base definition is virtual
+                    if (candidate.IsVirtual)
+                        continue;
+                    // base definition is non-virtual, but hiding is allowed anyway
+                    if (injectedType == null || result.DeclaringType!.IsAssignableFrom(injectedType))
```
Comment (peterwurzinger) [inline src/NeinLinq/InjectLambdaSignature.cs]: I'd go with
`injectedType is null`

Just for the sake of being cool.

File: test/NeinLinq.Fakes/InjectableQuery/FunctionsBase.cs [hunk 3]
```diff
@@ -83,5 +84,16 @@ public double VelocityWithNonPublicSibling(Dummy value)
...
+        public double VelocityWithHiddenSibling(Dummy value)
+        {
+            throw new NotSupportedException();
+        }
+
+        public Expression<Func<Dummy, double>> VelocityWithHiddenSibling()
+        {
+            return v => v.Distance / v.Time;
+        }
     }
```
Comment (peterwurzinger) [inline test/NeinLinq.Fakes/InjectableQuery/FunctionsBase.cs]: You could include a test for virtual members, to prove, that those are working also:

```C#
        [InjectLambda]
        public double VelocityWithVirtualSibling(Dummy value)
        {
            throw new NotSupportedException();
        }

        public abstract Expression<Func<Dummy, double>> VelocityWithVirtualSibling();
```

Continued in `ConcreteFunctions`

File: test/NeinLinq.Tests/InjectableQuery/QueryBaseTest.cs [hunk 4]
```diff
@@ -131,5 +131,16 @@ public void ShouldSucceedWithNonPublicSibling()
...
+        public void ShouldSucceedWithHiddenSibling()
+        {
+            var query = from d in data.ToInjectable()
+                        select ((FunctionsBase)functions).VelocityWithHiddenSibling(d);
+
+            var result = query.ToList();
+            
+            Assert.Equal(new[] { 200, .0, .125 }, result);
+        }
     }
```
Comment (peterwurzinger) [inline test/NeinLinq.Tests/InjectableQuery/QueryBaseTest.cs]: Test for virtual member:

```C#
        [Fact]
        public void ShouldSucceedWithVirtualSibling()
        {
            var query = from d in data.ToInjectable()
                        select functions.VelocityWithVirtualSibling(d);

            var result = query.ToList();

            Assert.Equal(new[] { 200.0, .0, .1 }, result);
        }
```

File: test/NeinLinq.Fakes/InjectableQuery/ConcreteFunctions.cs [hunk 5]
```diff
@@ -75,5 +75,10 @@ public new double VelocityWithMethodMetadata(Dummy value)
         {
             return v => Math.Round(v.Distance / v.Time, digits);
         }
+
+        public new Expression<Func<Dummy, double>> VelocityWithHiddenSibling()
+        {
+            throw new InvalidOperationException("Implementing sibling has been hidden.");
+        }
     }
```
Comment (peterwurzinger) [inline test/NeinLinq.Fakes/InjectableQuery/ConcreteFunctions.cs]: Test for virtual member:

```C#
        public override Expression<Func<Dummy, double>> VelocityWithVirtualSibling()
        {
            return v => Math.Round(v.Distance / v.Time, digits);
        }
```
